# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/runner/work/microNES/microNES

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/runner/work/microNES/microNES/build-web

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/runner/work/microNES/microNES/build-web/CMakeFiles /home/runner/work/microNES/microNES/build-web//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/runner/work/microNES/microNES/build-web/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named micrones_core

# Build rule for target.
micrones_core: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 micrones_core
.PHONY : micrones_core

# fast build rule for target.
micrones_core/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/micrones_core.dir/build.make CMakeFiles/micrones_core.dir/build
.PHONY : micrones_core/fast

#=============================================================================
# Target rules for targets named micrones_wasm

# Build rule for target.
micrones_wasm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 micrones_wasm
.PHONY : micrones_wasm

# fast build rule for target.
micrones_wasm/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/micrones_wasm.dir/build.make CMakeFiles/micrones_wasm.dir/build
.PHONY : micrones_wasm/fast

src/common/apu_micrones.o: src/common/apu_micrones.c.o
.PHONY : src/common/apu_micrones.o

# target to build an object file
src/common/apu_micrones.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/micrones_core.dir/build.make CMakeFiles/micrones_core.dir/src/common/apu_micrones.c.o
.PHONY : src/common/apu_micrones.c.o

src/common/apu_micrones.i: src/common/apu_micrones.c.i
.PHONY : src/common/apu_micrones.i

# target to preprocess a source file
src/common/apu_micrones.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/micrones_core.dir/build.make CMakeFiles/micrones_core.dir/src/common/apu_micrones.c.i
.PHONY : src/common/apu_micrones.c.i

src/common/apu_micrones.s: src/common/apu_micrones.c.s
.PHONY : src/common/apu_micrones.s

# target to generate assembly for a file
src/common/apu_micrones.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/micrones_core.dir/build.make CMakeFiles/micrones_core.dir/src/common/apu_micrones.c.s
.PHONY : src/common/apu_micrones.c.s

src/common/cart.o: src/common/cart.c.o
.PHONY : src/common/cart.o

# target to build an object file
src/common/cart.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/micrones_core.dir/build.make CMakeFiles/micrones_core.dir/src/common/cart.c.o
.PHONY : src/common/cart.c.o

src/common/cart.i: src/common/cart.c.i
.PHONY : src/common/cart.i

# target to preprocess a source file
src/common/cart.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/micrones_core.dir/build.make CMakeFiles/micrones_core.dir/src/common/cart.c.i
.PHONY : src/common/cart.c.i

src/common/cart.s: src/common/cart.c.s
.PHONY : src/common/cart.s

# target to generate assembly for a file
src/common/cart.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/micrones_core.dir/build.make CMakeFiles/micrones_core.dir/src/common/cart.c.s
.PHONY : src/common/cart.c.s

src/common/cpu6502.o: src/common/cpu6502.c.o
.PHONY : src/common/cpu6502.o

# target to build an object file
src/common/cpu6502.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/micrones_core.dir/build.make CMakeFiles/micrones_core.dir/src/common/cpu6502.c.o
.PHONY : src/common/cpu6502.c.o

src/common/cpu6502.i: src/common/cpu6502.c.i
.PHONY : src/common/cpu6502.i

# target to preprocess a source file
src/common/cpu6502.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/micrones_core.dir/build.make CMakeFiles/micrones_core.dir/src/common/cpu6502.c.i
.PHONY : src/common/cpu6502.c.i

src/common/cpu6502.s: src/common/cpu6502.c.s
.PHONY : src/common/cpu6502.s

# target to generate assembly for a file
src/common/cpu6502.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/micrones_core.dir/build.make CMakeFiles/micrones_core.dir/src/common/cpu6502.c.s
.PHONY : src/common/cpu6502.c.s

src/common/cpu6502_opcode.o: src/common/cpu6502_opcode.c.o
.PHONY : src/common/cpu6502_opcode.o

# target to build an object file
src/common/cpu6502_opcode.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/micrones_core.dir/build.make CMakeFiles/micrones_core.dir/src/common/cpu6502_opcode.c.o
.PHONY : src/common/cpu6502_opcode.c.o

src/common/cpu6502_opcode.i: src/common/cpu6502_opcode.c.i
.PHONY : src/common/cpu6502_opcode.i

# target to preprocess a source file
src/common/cpu6502_opcode.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/micrones_core.dir/build.make CMakeFiles/micrones_core.dir/src/common/cpu6502_opcode.c.i
.PHONY : src/common/cpu6502_opcode.c.i

src/common/cpu6502_opcode.s: src/common/cpu6502_opcode.c.s
.PHONY : src/common/cpu6502_opcode.s

# target to generate assembly for a file
src/common/cpu6502_opcode.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/micrones_core.dir/build.make CMakeFiles/micrones_core.dir/src/common/cpu6502_opcode.c.s
.PHONY : src/common/cpu6502_opcode.c.s

src/common/frame_pacer.o: src/common/frame_pacer.c.o
.PHONY : src/common/frame_pacer.o

# target to build an object file
src/common/frame_pacer.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/micrones_core.dir/build.make CMakeFiles/micrones_core.dir/src/common/frame_pacer.c.o
.PHONY : src/common/frame_pacer.c.o

src/common/frame_pacer.i: src/common/frame_pacer.c.i
.PHONY : src/common/frame_pacer.i

# target to preprocess a source file
src/common/frame_pacer.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/micrones_core.dir/build.make CMakeFiles/micrones_core.dir/src/common/frame_pacer.c.i
.PHONY : src/common/frame_pacer.c.i

src/common/frame_pacer.s: src/common/frame_pacer.c.s
.PHONY : src/common/frame_pacer.s

# target to generate assembly for a file
src/common/frame_pacer.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/micrones_core.dir/build.make CMakeFiles/micrones_core.dir/src/common/frame_pacer.c.s
.PHONY : src/common/frame_pacer.c.s

src/common/input.o: src/common/input.c.o
.PHONY : src/common/input.o

# target to build an object file
src/common/input.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/micrones_core.dir/build.make CMakeFiles/micrones_core.dir/src/common/input.c.o
.PHONY : src/common/input.c.o

src/common/input.i: src/common/input.c.i
.PHONY : src/common/input.i

# target to preprocess a source file
src/common/input.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/micrones_core.dir/build.make CMakeFiles/micrones_core.dir/src/common/input.c.i
.PHONY : src/common/input.c.i

src/common/input.s: src/common/input.c.s
.PHONY : src/common/input.s

# target to generate assembly for a file
src/common/input.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/micrones_core.dir/build.make CMakeFiles/micrones_core.dir/src/common/input.c.s
.PHONY : src/common/input.c.s

src/common/mmc1.o: src/common/mmc1.c.o
.PHONY : src/common/mmc1.o

# target to build an object file
src/common/mmc1.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/micrones_core.dir/build.make CMakeFiles/micrones_core.dir/src/common/mmc1.c.o
.PHONY : src/common/mmc1.c.o

src/common/mmc1.i: src/common/mmc1.c.i
.PHONY : src/common/mmc1.i

# target to preprocess a source file
src/common/mmc1.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/micrones_core.dir/build.make CMakeFiles/micrones_core.dir/src/common/mmc1.c.i
.PHONY : src/common/mmc1.c.i

src/common/mmc1.s: src/common/mmc1.c.s
.PHONY : src/common/mmc1.s

# target to generate assembly for a file
src/common/mmc1.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/micrones_core.dir/build.make CMakeFiles/micrones_core.dir/src/common/mmc1.c.s
.PHONY : src/common/mmc1.c.s

src/common/nes.o: src/common/nes.c.o
.PHONY : src/common/nes.o

# target to build an object file
src/common/nes.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/micrones_core.dir/build.make CMakeFiles/micrones_core.dir/src/common/nes.c.o
.PHONY : src/common/nes.c.o

src/common/nes.i: src/common/nes.c.i
.PHONY : src/common/nes.i

# target to preprocess a source file
src/common/nes.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/micrones_core.dir/build.make CMakeFiles/micrones_core.dir/src/common/nes.c.i
.PHONY : src/common/nes.c.i

src/common/nes.s: src/common/nes.c.s
.PHONY : src/common/nes.s

# target to generate assembly for a file
src/common/nes.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/micrones_core.dir/build.make CMakeFiles/micrones_core.dir/src/common/nes.c.s
.PHONY : src/common/nes.c.s

src/common/nrom.o: src/common/nrom.c.o
.PHONY : src/common/nrom.o

# target to build an object file
src/common/nrom.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/micrones_core.dir/build.make CMakeFiles/micrones_core.dir/src/common/nrom.c.o
.PHONY : src/common/nrom.c.o

src/common/nrom.i: src/common/nrom.c.i
.PHONY : src/common/nrom.i

# target to preprocess a source file
src/common/nrom.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/micrones_core.dir/build.make CMakeFiles/micrones_core.dir/src/common/nrom.c.i
.PHONY : src/common/nrom.c.i

src/common/nrom.s: src/common/nrom.c.s
.PHONY : src/common/nrom.s

# target to generate assembly for a file
src/common/nrom.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/micrones_core.dir/build.make CMakeFiles/micrones_core.dir/src/common/nrom.c.s
.PHONY : src/common/nrom.c.s

src/common/ppu.o: src/common/ppu.c.o
.PHONY : src/common/ppu.o

# target to build an object file
src/common/ppu.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/micrones_core.dir/build.make CMakeFiles/micrones_core.dir/src/common/ppu.c.o
.PHONY : src/common/ppu.c.o

src/common/ppu.i: src/common/ppu.c.i
.PHONY : src/common/ppu.i

# target to preprocess a source file
src/common/ppu.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/micrones_core.dir/build.make CMakeFiles/micrones_core.dir/src/common/ppu.c.i
.PHONY : src/common/ppu.c.i

src/common/ppu.s: src/common/ppu.c.s
.PHONY : src/common/ppu.s

# target to generate assembly for a file
src/common/ppu.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/micrones_core.dir/build.make CMakeFiles/micrones_core.dir/src/common/ppu.c.s
.PHONY : src/common/ppu.c.s

src/web/web_main.o: src/web/web_main.c.o
.PHONY : src/web/web_main.o

# target to build an object file
src/web/web_main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/micrones_wasm.dir/build.make CMakeFiles/micrones_wasm.dir/src/web/web_main.c.o
.PHONY : src/web/web_main.c.o

src/web/web_main.i: src/web/web_main.c.i
.PHONY : src/web/web_main.i

# target to preprocess a source file
src/web/web_main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/micrones_wasm.dir/build.make CMakeFiles/micrones_wasm.dir/src/web/web_main.c.i
.PHONY : src/web/web_main.c.i

src/web/web_main.s: src/web/web_main.c.s
.PHONY : src/web/web_main.s

# target to generate assembly for a file
src/web/web_main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/micrones_wasm.dir/build.make CMakeFiles/micrones_wasm.dir/src/web/web_main.c.s
.PHONY : src/web/web_main.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... micrones_core"
	@echo "... micrones_wasm"
	@echo "... src/common/apu_micrones.o"
	@echo "... src/common/apu_micrones.i"
	@echo "... src/common/apu_micrones.s"
	@echo "... src/common/cart.o"
	@echo "... src/common/cart.i"
	@echo "... src/common/cart.s"
	@echo "... src/common/cpu6502.o"
	@echo "... src/common/cpu6502.i"
	@echo "... src/common/cpu6502.s"
	@echo "... src/common/cpu6502_opcode.o"
	@echo "... src/common/cpu6502_opcode.i"
	@echo "... src/common/cpu6502_opcode.s"
	@echo "... src/common/frame_pacer.o"
	@echo "... src/common/frame_pacer.i"
	@echo "... src/common/frame_pacer.s"
	@echo "... src/common/input.o"
	@echo "... src/common/input.i"
	@echo "... src/common/input.s"
	@echo "... src/common/mmc1.o"
	@echo "... src/common/mmc1.i"
	@echo "... src/common/mmc1.s"
	@echo "... src/common/nes.o"
	@echo "... src/common/nes.i"
	@echo "... src/common/nes.s"
	@echo "... src/common/nrom.o"
	@echo "... src/common/nrom.i"
	@echo "... src/common/nrom.s"
	@echo "... src/common/ppu.o"
	@echo "... src/common/ppu.i"
	@echo "... src/common/ppu.s"
	@echo "... src/web/web_main.o"
	@echo "... src/web/web_main.i"
	@echo "... src/web/web_main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

