#include "cpu6502_opcode.h"

static const Cpu6502OpcodeInfo cpu6502_opcode_table[256] = {
#define OP(code, mnemonic_text, mode_text) \
    [code] = { mnemonic_text, mode_text, true, true }
/* Illegal but implemented: official=false, supported=true */
#define IL(code, mnemonic_text, mode_text) \
    [code] = { mnemonic_text, mode_text, false, true }
    OP(0x00, "BRK", "impl"),
    OP(0x01, "ORA", "(ind,X)"),
    OP(0x05, "ORA", "zp"),
    OP(0x06, "ASL", "zp"),
    OP(0x08, "PHP", "impl"),
    OP(0x09, "ORA", "#imm"),
    OP(0x0a, "ASL", "A"),
    OP(0x0d, "ORA", "abs"),
    OP(0x0e, "ASL", "abs"),
    OP(0x10, "BPL", "rel"),
    OP(0x11, "ORA", "(ind),Y"),
    OP(0x15, "ORA", "zp,X"),
    OP(0x16, "ASL", "zp,X"),
    OP(0x18, "CLC", "impl"),
    OP(0x19, "ORA", "abs,Y"),
    OP(0x1d, "ORA", "abs,X"),
    OP(0x1e, "ASL", "abs,X"),
    OP(0x20, "JSR", "abs"),
    OP(0x21, "AND", "(ind,X)"),
    OP(0x24, "BIT", "zp"),
    OP(0x25, "AND", "zp"),
    OP(0x26, "ROL", "zp"),
    OP(0x28, "PLP", "impl"),
    OP(0x29, "AND", "#imm"),
    OP(0x2a, "ROL", "A"),
    OP(0x2c, "BIT", "abs"),
    OP(0x2d, "AND", "abs"),
    OP(0x2e, "ROL", "abs"),
    OP(0x30, "BMI", "rel"),
    OP(0x31, "AND", "(ind),Y"),
    OP(0x35, "AND", "zp,X"),
    OP(0x36, "ROL", "zp,X"),
    OP(0x38, "SEC", "impl"),
    OP(0x39, "AND", "abs,Y"),
    OP(0x3d, "AND", "abs,X"),
    OP(0x3e, "ROL", "abs,X"),
    OP(0x40, "RTI", "impl"),
    OP(0x41, "EOR", "(ind,X)"),
    OP(0x45, "EOR", "zp"),
    OP(0x46, "LSR", "zp"),
    OP(0x48, "PHA", "impl"),
    OP(0x49, "EOR", "#imm"),
    OP(0x4a, "LSR", "A"),
    OP(0x4c, "JMP", "abs"),
    OP(0x4d, "EOR", "abs"),
    OP(0x4e, "LSR", "abs"),
    OP(0x50, "BVC", "rel"),
    OP(0x51, "EOR", "(ind),Y"),
    OP(0x55, "EOR", "zp,X"),
    OP(0x56, "LSR", "zp,X"),
    OP(0x58, "CLI", "impl"),
    OP(0x59, "EOR", "abs,Y"),
    OP(0x5d, "EOR", "abs,X"),
    OP(0x5e, "LSR", "abs,X"),
    OP(0x60, "RTS", "impl"),
    OP(0x61, "ADC", "(ind,X)"),
    OP(0x65, "ADC", "zp"),
    OP(0x66, "ROR", "zp"),
    OP(0x68, "PLA", "impl"),
    OP(0x69, "ADC", "#imm"),
    OP(0x6a, "ROR", "A"),
    OP(0x6c, "JMP", "(ind)"),
    OP(0x6d, "ADC", "abs"),
    OP(0x6e, "ROR", "abs"),
    OP(0x70, "BVS", "rel"),
    OP(0x71, "ADC", "(ind),Y"),
    OP(0x75, "ADC", "zp,X"),
    OP(0x76, "ROR", "zp,X"),
    OP(0x78, "SEI", "impl"),
    OP(0x79, "ADC", "abs,Y"),
    OP(0x7d, "ADC", "abs,X"),
    OP(0x7e, "ROR", "abs,X"),
    OP(0x81, "STA", "(ind,X)"),
    OP(0x84, "STY", "zp"),
    OP(0x85, "STA", "zp"),
    OP(0x86, "STX", "zp"),
    OP(0x88, "DEY", "impl"),
    OP(0x8a, "TXA", "impl"),
    OP(0x8c, "STY", "abs"),
    OP(0x8d, "STA", "abs"),
    OP(0x8e, "STX", "abs"),
    OP(0x90, "BCC", "rel"),
    OP(0x91, "STA", "(ind),Y"),
    OP(0x94, "STY", "zp,X"),
    OP(0x95, "STA", "zp,X"),
    OP(0x96, "STX", "zp,Y"),
    OP(0x98, "TYA", "impl"),
    OP(0x99, "STA", "abs,Y"),
    OP(0x9a, "TXS", "impl"),
    OP(0x9d, "STA", "abs,X"),
    OP(0xa0, "LDY", "#imm"),
    OP(0xa1, "LDA", "(ind,X)"),
    OP(0xa2, "LDX", "#imm"),
    OP(0xa4, "LDY", "zp"),
    OP(0xa5, "LDA", "zp"),
    OP(0xa6, "LDX", "zp"),
    OP(0xa8, "TAY", "impl"),
    OP(0xa9, "LDA", "#imm"),
    OP(0xaa, "TAX", "impl"),
    OP(0xac, "LDY", "abs"),
    OP(0xad, "LDA", "abs"),
    OP(0xae, "LDX", "abs"),
    OP(0xb0, "BCS", "rel"),
    OP(0xb1, "LDA", "(ind),Y"),
    OP(0xb4, "LDY", "zp,X"),
    OP(0xb5, "LDA", "zp,X"),
    OP(0xb6, "LDX", "zp,Y"),
    OP(0xb8, "CLV", "impl"),
    OP(0xb9, "LDA", "abs,Y"),
    OP(0xba, "TSX", "impl"),
    OP(0xbc, "LDY", "abs,X"),
    OP(0xbd, "LDA", "abs,X"),
    OP(0xbe, "LDX", "abs,Y"),
    OP(0xc0, "CPY", "#imm"),
    OP(0xc1, "CMP", "(ind,X)"),
    OP(0xc4, "CPY", "zp"),
    OP(0xc5, "CMP", "zp"),
    OP(0xc6, "DEC", "zp"),
    OP(0xc8, "INY", "impl"),
    OP(0xc9, "CMP", "#imm"),
    OP(0xca, "DEX", "impl"),
    OP(0xcc, "CPY", "abs"),
    OP(0xcd, "CMP", "abs"),
    OP(0xce, "DEC", "abs"),
    OP(0xd0, "BNE", "rel"),
    OP(0xd1, "CMP", "(ind),Y"),
    OP(0xd5, "CMP", "zp,X"),
    OP(0xd6, "DEC", "zp,X"),
    OP(0xd8, "CLD", "impl"),
    OP(0xd9, "CMP", "abs,Y"),
    OP(0xdd, "CMP", "abs,X"),
    OP(0xde, "DEC", "abs,X"),
    OP(0xe0, "CPX", "#imm"),
    OP(0xe1, "SBC", "(ind,X)"),
    OP(0xe4, "CPX", "zp"),
    OP(0xe5, "SBC", "zp"),
    OP(0xe6, "INC", "zp"),
    OP(0xe8, "INX", "impl"),
    OP(0xe9, "SBC", "#imm"),
    OP(0xea, "NOP", "impl"),
    OP(0xec, "CPX", "abs"),
    OP(0xed, "SBC", "abs"),
    OP(0xee, "INC", "abs"),
    OP(0xf0, "BEQ", "rel"),
    OP(0xf1, "SBC", "(ind),Y"),
    OP(0xf5, "SBC", "zp,X"),
    OP(0xf6, "INC", "zp,X"),
    OP(0xf8, "SED", "impl"),
    OP(0xf9, "SBC", "abs,Y"),
    OP(0xfd, "SBC", "abs,X"),
    OP(0xfe, "INC", "abs,X"),
    /* Illegal opcodes */
    IL(0x1a, "NOP", "impl"),  IL(0x3a, "NOP", "impl"),  IL(0x5a, "NOP", "impl"),
    IL(0x7a, "NOP", "impl"),  IL(0xda, "NOP", "impl"),  IL(0xfa, "NOP", "impl"),
    IL(0x80, "NOP", "#imm"),  IL(0x82, "NOP", "#imm"),  IL(0x89, "NOP", "#imm"),
    IL(0xc2, "NOP", "#imm"),  IL(0xe2, "NOP", "#imm"),
    IL(0x04, "NOP", "zp"),    IL(0x44, "NOP", "zp"),    IL(0x64, "NOP", "zp"),
    IL(0x14, "NOP", "zp,X"),  IL(0x34, "NOP", "zp,X"),  IL(0x54, "NOP", "zp,X"),
    IL(0x74, "NOP", "zp,X"),  IL(0xd4, "NOP", "zp,X"),  IL(0xf4, "NOP", "zp,X"),
    IL(0x0c, "NOP", "abs"),
    IL(0x1c, "NOP", "abs,X"), IL(0x3c, "NOP", "abs,X"), IL(0x5c, "NOP", "abs,X"),
    IL(0x7c, "NOP", "abs,X"), IL(0xdc, "NOP", "abs,X"), IL(0xfc, "NOP", "abs,X"),
    IL(0x0b, "ANC", "#imm"),
    IL(0x03, "SLO", "(ind,X)"), IL(0x07, "SLO", "zp"),   IL(0x0f, "SLO", "abs"),
    IL(0x13, "SLO", "(ind),Y"), IL(0x17, "SLO", "zp,X"), IL(0x1b, "SLO", "abs,Y"),
    IL(0x1f, "SLO", "abs,X"),
    IL(0x2b, "ANC", "#imm"),
    IL(0x23, "RLA", "(ind,X)"), IL(0x27, "RLA", "zp"),   IL(0x2f, "RLA", "abs"),
    IL(0x33, "RLA", "(ind),Y"), IL(0x37, "RLA", "zp,X"), IL(0x3b, "RLA", "abs,Y"),
    IL(0x3f, "RLA", "abs,X"),
    IL(0x4b, "ALR", "#imm"),
    IL(0x43, "SRE", "(ind,X)"), IL(0x47, "SRE", "zp"),   IL(0x4f, "SRE", "abs"),
    IL(0x53, "SRE", "(ind),Y"), IL(0x57, "SRE", "zp,X"), IL(0x5b, "SRE", "abs,Y"),
    IL(0x5f, "SRE", "abs,X"),
    IL(0x6b, "ARR", "#imm"),
    IL(0x63, "RRA", "(ind,X)"), IL(0x67, "RRA", "zp"),   IL(0x6f, "RRA", "abs"),
    IL(0x73, "RRA", "(ind),Y"), IL(0x77, "RRA", "zp,X"), IL(0x7b, "RRA", "abs,Y"),
    IL(0x7f, "RRA", "abs,X"),
    IL(0x83, "SAX", "(ind,X)"), IL(0x87, "SAX", "zp"),   IL(0x8f, "SAX", "abs"),
    IL(0x97, "SAX", "zp,Y"),
    IL(0xa3, "LAX", "(ind,X)"), IL(0xa7, "LAX", "zp"),   IL(0xaf, "LAX", "abs"),
    IL(0xab, "LAX", "#imm"),
    IL(0xb3, "LAX", "(ind),Y"), IL(0xb7, "LAX", "zp,Y"), IL(0xbf, "LAX", "abs,Y"),
    IL(0xcb, "AXS", "#imm"),
    IL(0xc3, "DCP", "(ind,X)"), IL(0xc7, "DCP", "zp"),   IL(0xcf, "DCP", "abs"),
    IL(0xd3, "DCP", "(ind),Y"), IL(0xd7, "DCP", "zp,X"), IL(0xdb, "DCP", "abs,Y"),
    IL(0xdf, "DCP", "abs,X"),
    IL(0xeb, "SBC", "#imm"),
    IL(0xe3, "ISB", "(ind,X)"), IL(0xe7, "ISB", "zp"),   IL(0xef, "ISB", "abs"),
    IL(0xf3, "ISB", "(ind),Y"), IL(0xf7, "ISB", "zp,X"), IL(0xfb, "ISB", "abs,Y"),
    IL(0xff, "ISB", "abs,X"),
#undef IL
#undef OP
};

const Cpu6502OpcodeInfo *cpu6502_opcode_info(uint8_t opcode) {
    static const Cpu6502OpcodeInfo illegal = { "???", "illegal", false, false };
    const Cpu6502OpcodeInfo *info = &cpu6502_opcode_table[opcode];

    if (info->mnemonic == 0) {
        return &illegal;
    }
    return info;
}
