#ifndef SMB2350_RUNTIME_CONFIG_H
#define SMB2350_RUNTIME_CONFIG_H

#ifndef SMB2350_ENABLE_RUNTIME_DIAGNOSTICS
#define SMB2350_ENABLE_RUNTIME_DIAGNOSTICS 1
#endif

#ifndef SMB2350_ENABLE_APU_DEBUG_METRICS
#define SMB2350_ENABLE_APU_DEBUG_METRICS SMB2350_ENABLE_RUNTIME_DIAGNOSTICS
#endif

#ifndef SMB2350_ENABLE_APU_PCM_OUTPUT
#define SMB2350_ENABLE_APU_PCM_OUTPUT 1
#endif

#endif
