M48
; DRILL file KiCad 10.0.0 date 2026-05-07T21:01:34
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-07T21:01:34-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.700
%
G90
G05
T1
X90.95Y-78.15
X118.45Y-78.15
T2
X112.6Y-108.45
X157.6Y-119.4
X157.85Y-69.5
M30
