M48
; DRILL file KiCad 10.0.0 date 2026-05-22T19:45:41
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-22T19:45:41-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.700
%
G90
G05
T1
X61.25Y-78.5
X88.75Y-78.5
T2
X64.2Y-117.6
X64.4Y-94.1
X157.0Y-69.9
X157.3Y-132.2
M30
